---
title: Snowmelt estimation, energy balance approach (not used)
date: Last compiled 2021-10-18
output: 
  html_document:
    toc: true
    toc_float: true
---


# Snowmelt estimation

Daily accumulated snowmelt is collected from SNODAS. This data

**TODO**

- data used is SNODAS
- prior to 2010-09-01, estimated using snowmelt model described below


## Snowmelt model

Snowpack melt is computed using a temperature-index/cold-content approach that closely
follows the methodology of DeWalle and Rango (2008). The method's
complexity lies somewhere in between the empirical degree-day approach
and the physics-based energy-balance approach. The method has the same
data requirements as the degree-day approach (namely, temperature and
precipitation), yet simulates snowpack metamorphism processes
to account for the refreeze of liquid water held in pore spaces. 
The model can produce estimates of snowpack density, depth, and temperature.

The model represents the snowpack as a single layer with uniform
temperature with depth. The model represents processes at the point scale and does not consider spatial
distribution within some conceptual land area (i.e., zero-dimensional). 
<!-- That said, by virtue of the model being applied in a spatially distibuted manner, mesoscale snowpack patterns will be realized on the basis of local slope and aspect which effectively adjusts the duration of sunshine exposure. -->

The water balance within the snowpack is accounted on the basis of
snowpack snow water equivalent ($P_\text{swe}$), which is the total mass
of water in both ice and liquid form. The liquid portion of
$P_\text{swe}$ is accounted for as the snowpack liquid water content
($P_\text{lwc}$). While the cold-content dictates the energetic state of
the snowpack, differences in $P_\text{swe}$ and $P_\text{lwc}$ dictate
the mass state of the snowpack; for example, the fraction of ice within
the snowpack can be determined by:

$$
  f_\text{ice}=1-\frac{P_\text{lwc}}{P_\text{swe}}.
$$

By accounting for the snowpack's energy and mass states, the balance between liquid and ice varies constantly, a process termed snowpack metamorphism. Eventually, as the winter ends, the balance heavily favours the liquid form and the pack melts away.

### Theory

The model begins first by assessing whether an existing snowpack exists.
Air temperature ($T_a$) for this model is set to daily mean
temperature. If snowfall is observed, then it is added to the existing
pack or else a new snowpack is created. The density of fresh
snowfall ($\rho_{SF}$) is assumed to be linearly correlated to air
temperature as demonstrated in Judson and Doesken (2000), and is given
by:

$$
  \rho_{SF}=
  \begin{cases}
    \rho_{0°\text{C}} & \quad T_a \geq 0°\text{C} \\
    \text{max}\left(m_{\rho}T_a+\rho_{0°\text{C}} \text{, } \rho_{SF_{min}}\right) &  \quad \text{otherwise},
  \end{cases}
$$

where $\rho_{0°\text{C}}$ is the density of
snowfall warmed to 0°C, $\rho_{SF_{min}}$ is the lower limit to
snowfall density (assumed 25 kg/m³), and
$m_{\rho}$ is the slope of the temperature-density relationship and assumes a linear relationship between temperature and snowfall density. A value of 5.5 kg/m³/°C is applied (Judson and Doesken, 2000).

### Mass balance

Next, snowfall is added to the snowpack, adjusting pack density
($\rho_p$) by:

$$
  \rho_p=\frac{P_\text{swe}\cdot\rho_{p_\ell}+SF_\text{swe}\cdot\rho_{SF}}{P_\text{swe}+SF_\text{swe}},
$$

where $P_\text{swe}$ is the pack snow water
equivalent, $\rho_{p_\ell}$ is the snowpack density prior to the
addition of snow, and $SF_\text{swe}$ is the snowfall water equivalent.
$P_\text{swe}$ is then updated by adding $SF_\text{swe}$.

Temperature of the snowpack surface ($T_s$) is set to $T_a$ (or 0°C, whichever is less) if the pack
is new or snowfall water equivalent ($SF_\text{swe}$) exceeds 5 mm, otherwise:

$$
  T_s = \text{max}\left(T_{s_\ell}+C_\text{TSF}\left(T_a-T_{s_\ell}\right)\text{, } 0\right),
$$

where $T_{s_\ell}$ is the snow surface temperature
prior to adjustment, and $C_\text{TSF}$ is the surface temperature
adjustment factor. 
<!-- $T_s$ is restricted to an upper-limit of $0°\text{C}$. -->

The degree-day factor ($\text{DDF}$) is then computed from snowpack density
following the approach given by Martinec (1960). The idea here is that
over time, as the snowpack settles, its albedo also decreases causing
the pack to more susceptible to melt. This provides a convenient and
indirect means of relating snow melt potential to snow pack age. DDF is
adjusted by (Martinec, 1960):

$$
  \text{DDF} = C_\text{DDF}\frac{\rho_p}{\rho_w},
$$

where $\rho_w$ is the density of liquid water at
$0°\text{C}$ ($\approx$ 999.84 kg/m³), and
$C_\text{DDF}$ is the density-DDF adjustment factor. Next, potential
snowmelt ($M_\text{swe}$) is computed by:

$$
  M_\text{swe} = \text{min}\left(\text{max}\left(\text{DDF}\cdot\left(T_a-T_b\right)\text{, } 0\right)\text{, } P_\text{swe}\right),
$$

where $T_b$ is a base (or critical) temperature from
which melt can occur. Any potential melt is added to the pack liquid
water content store ($P_\text{lwc}$), and with knowledge of the fraction of water in liquid form ($f_\text{lw}$), pack density is adjusted
by:

$$
  \rho_p=f_\text{lw}\left(\rho_w-\rho_\text{froz}\right) + \rho_\text{froz},
$$

where $\rho_\text{froz}$ is the density of the dry/frozen
snowpack (i.e., the pack with all liquid water ($P_\text{lwc}$) removed) and is given by:

$$
  \rho_\text{froz}=\frac{P_\text{swe}\cdot\rho_p-P_\text{lwc}\cdot\rho_w}{P_\text{swe}-P_\text{lwc}}.
$$

<!-- and -->

<!-- $$ -->
<!--   f_\text{lw}=\frac{\left(M_\text{swe}+P_\text{lwc}\right)}{P_\text{swe}}. -->
<!-- $$ -->

If rainfall ($R$) occurs its amount is added to both $P_\text{swe}$ and $P_\text{lwc}$ and the pack density is adjusted by:

$$
  \rho_p=\frac{P_\text{swe}\cdot\rho_{p_\ell}+R \rho_w}{P_\text{swe}+R}.
$$

### Energy balance

Next, should liquid water be contained within the snowpack, cold content
of the pack ($CC$) must be satisfied before drainage from the pack can
ensue. 
Cold-content is the amount of water that needs to freeze, in order for the pack to become "ripe" (pack temperature of 0°C) and loses the ability to freeze any more water. Like the degree-day and pack temperature equations, the cold-content is adjusted by:

$$
  CC = \text{min}\left(CC+C_\text{CCF}\left(T_s-T_a\right)\text{, } 0\right),
$$
where $C_\text{CCF}$ is the cold-content temperature index (DeWalle and Rango, 2000).


Liquid water freezing internally to the snowpack causes its
density to be adjusted by:

$$
  \rho_p=f_\text{lw}\left(\rho_i-\rho_w\right)+\rho_{p_\ell},
$$

where $\rho_i$ is the density of ice at $0°\text{C}$
($\approx$ 917,kg/m³), and the fraction of the
snowpack mass in liquid form is given by:

$$
  f_\text{lw}=
  \begin{cases}
    \frac{P_\text{lwc}}{P_\text{swe}} & \quad P_\text{lwc} \leq \text{CC}\\
    \frac{\text{CC}}{P_\text{swe}} & \quad \text{otherwise}\\
  \end{cases}.
$$

The amount frozen to the pack is subtracted from
$P_\text{lwc}$.

In the final step, liquid water exceeding the snowpack liquid water
holding capacity is allowed to drain from the base of the pack. When
$P_\text{swe}=P_\text{lwc}$, i.e., the snowpack is composed solely of
liquid water, the entirety of the snowpack water equivalent is allowed
to drain and the snow pack layer is eliminated. Pack drainage is given
by:

$$
  P_\text{drn}=
  \begin{cases}
    P_\text{lwc}-P_\text{lwcap} & \quad P_\text{lwc} \geq P_\text{lwc}\\
    0 & \quad \text{otherwise}\\
  \end{cases}.
  \label{eqPdrn}
$$

Snowpack liquid water holding capacity
($P_\text{lwcap}$) is defined by:

$$
  P_\text{lwcap}=\phi S_\text{cap} d_p,
$$

where $S_\text{cap}$ is the snowpack liquid water
retention capacity as a degree of pore space saturation ($\approx 0.05$;
DeWalle and Rango, 2008), $d_p$ is pack depth, and $\phi$ is pack
porosity, defined by:

$$
  \phi=1-\frac{\rho_p-\rho_w\theta_w}{\rho_i},
$$

where $\theta_w=S_w\phi=P_\text{lwc}/d_p$ is the
volumetric liquid water content (i.e., volume of liquid water to volume
of snowpack).

All liquid water above $P_\text{lwcap}$ is added to pack drainage
($P_\text{drn}$) and removed from $P_\text{swe}$, $P_\text{lwc}$. Pack
density is adjusted according to:

$$
  \rho_p=\frac{\left(P_\text{lwc}-P_\text{drn}\right)\rho_w+\left(P_\text{swe}-P_\text{lwc}\right)\rho_\text{froz}}{P_\text{swe}-P_\text{drn}}
$$

Pack densification (i.e., settlement) due to internal redistribution of water through phase changes is implicitly handled by this equation.

<!-- Pack densification (i.e., settlement) is caused by two processes: -->
<!-- internal redistribution of water through phase changes and consolidation -->
<!-- though the weight of the snowpack. The former process is implicitly -->
<!-- handled by the model described above, while the latter is handled by a -->
<!-- settlement factor given by: -->

<!-- $$ -->
<!--   \rho_p= -->
<!--   \begin{cases} -->
<!--     \rho_{p_\ell}\left(\frac{\rho_i}{\rho_\text{froz}}\right)^{C_\text{dens}} & \quad {p_\ell}<\rho_i \\ -->
<!--     \rho_{p_\ell}  & \quad \text{otherwise} -->
<!--   \end{cases} -->
<!-- $$ -->

### Model calibration

<!-- Data from 537 current and historical meteorological stations were collected -->
<!-- and screened for snow depth data. Of these stations, the data were -->
<!-- further screened for winter seasons (October through May) for complete -->
<!-- climate data reported for more than 100 consecutive days. Based on the -->
<!-- screening, 100 stations were selected, some having multiple season -->
<!-- meeting the screening criteria. In all, 233 snow seasons were collected -->
<!-- and were reordered into a continuous 233-year dataset for model -->
<!-- validation. -->

<!-- **TODO** -->

The calibration of the model was targeted at matching measured snowpack depths. It is likely that relying on snowpack depth measurements is the greatest source of error in this process. Preferably, knowing the snow water content (i.e., SWE) of the snowpack would improve upon this limitation. It is understood, however, that much greater resources are required in collecting SWE---so we're stuck with pack depth.

The trouble with snowpack depth is that to convert it to smowmelt, one needs knowledge of the snowpack's density--a very hard process to model. Nonetheless, snow abalation models, like the one described above, tend to match well to measured snowdepth.

A total of 66 meteorological stations (current and historic) kept records of snowpack depth. Of these, 28 stations had not recorded the necessary inputs (precipitation and temperature) to operate the methodology above; they were discarded. Another 10 were rejected do to suspect data quality. The remaining 28 are shown here:


The model parameters ($C_\text{TSF}$, $C_\text{DDF}$, $C_\text{CCF}$ and $T_b$) were optimized by machine learning. Here the shuffled complex evolution scheme (Duan et.al., 1993) is employed.







# References

Judson and Doesken, 2000

DeWalle Rango, 2000

Martinec, 1960

Duan, Q.Y., V.K. Gupta, and S. Sorooshian, 1993. Shuffled Complex Evolution Approach for Effective and Efficient Global Minimization. Journal of Optimization Theory and Applications 76(3) pp.501-521.